# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:6

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
before_script:
    - npm install

stages: deploy

deploy-app:
    stage: deploy
    only:
        - master 
    script:
        - npm start
    artifacts:
        - public
        

